### ISSUE TITLE
Current site deploy throws 502

### ISSUE THREAD

**Issue by dcalhoun** [danieldunderfelt/libsize#1]
Having trouble accessing the deployed site for this project. Is this site still maintained?

![libsize-502](https://user-images.githubusercontent.com/438664/32628945-2ea5ecc4-c55d-11e7-9ac1-3e1c1dda7c2d.png)

**Comment by danieldunderfelt** [comment]
Hi!

Sorry for the late answer. I am no longer maintaining libsize.com, but I still have the domain so I might put it up somewhere else. Thanks for your interest!

**Comment by dcalhoun** [comment]
No worries. Might be a good idea to mark the repo us unmaintained and remove the domain links. Thanks!
